import json
import string
import uuid
import logging
import re
import os
import time
from typing import List, Dict, Any, Optional
from concurrent.futures import ThreadPoolExecutor

import requests

from pydantic import BaseModel
from autogen_core import (
    DefaultTopicId,
    MessageContext,
    RoutedAgent,
    SingleThreadedAgentRuntime,
    TopicId,
    TypeSubscription,
    message_handler,
)

from autogen_core.models import (
    ChatCompletionClient,
    LLMMessage,
    SystemMessage,
    UserMessage,
    AssistantMessage,
)

from autogen_ext.models.ollama import OllamaChatCompletionClient

from rich.console import Console
from rich.markdown import Markdown
from prompt_toolkit import prompt
from prompt_toolkit import PromptSession

from rag.llm import max_token_truncate, assemble_knowledge_base
from parse.parser import Chunk, ChunkType
from utils import pretty_format

chat_host = 'http://127.0.0.1:11434'
search_host = 'http://127.0.0.1:4567/search'
chat_model = 'qwen3:30b-a3b'

max_token_num = 80 * 1024
is_generating = False

model_client = OllamaChatCompletionClient(model=chat_model, host=chat_host)


# ------------------------------------------------------------------------------
# Util funcs
def _agent_log(content: str) -> str:
    return '\n' + '-' * 80 + '\n\n' + content + '\n\n' + '-' * 80 + '\n\n'


def _escape_markdown(text: str) -> str:
    if text is None:
        return text

    text = re.sub(r"<(.?)", r"&lt;\1", text)
    text = re.sub(r"(.?)>", r"\1&gt;", text)

    return text


# ------------------------------------------------------------------------------
# Messages


class ChatMessage(BaseModel):
    """
    Group chat messages, generated by `user` / `system` / `assistance`.
    """
    body: LLMMessage
    meta: Optional[Dict[Any, Any]] = None  # extra meta data.


class QueryParseResult(BaseModel):
    rational: str  # Breif explaination why the action is determined.
    action: str  # Action
    original_query: str  # User original query


class SearchRequest(BaseModel):
    query: List[str]  # list of queries to execute


class GenerationRequest(BaseModel):
    pass


# ------------------------------------------------------------------------------
# Agents
# Query master
class QueryMasterAgent(RoutedAgent):
    """Agent that parses user input query and recognize user intent"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        query_rewriter_topic_type: str,
        chat_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._model_client = model_client
        self._chat_history: List[LLMMessage] = []
        self._query_rewriter_topic_type = query_rewriter_topic_type
        self._chat_topic_type = chat_topic_type

    @message_handler
    async def handle_chat_message(self, message: ChatMessage, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type} handle chat message:\n{pretty_format(message, indent=1)}')

        if isinstance(message.body, SystemMessage):
            # insert or update system message
            if len(self._chat_history) > 0 and isinstance(self._chat_history[0].body, SystemMessage):
                self._chat_history[0] = message
            else:
                self._chat_history.insert(0, message)
            return

        if isinstance(message.body, AssistantMessage):
            # append message but donot trigger query parsing.
            self._chat_history.append(message)
            return

        # append user message to chat history
        self._chat_history.append(message)

        _parse_prompt = """
        You are a query understanding agent in a research conversation and working with other agents. 
        Your role is to parse user query and determine what to do next given conversation history.

        Below is history conversations:

        {history_conversation}

        Above is history conversations.

        Instructions:
        - User query may not necessary trigger query action when history information is sufficient. In this case you can just return 'context_sufficient'.
        - If current context is not sufficient to answer user question, you need to return `query`.


        Format:
        - Format your response as a JSON object with ALL two of these exact keys:
            - "rational": "Brief explanation of why the action is necessary.",
            - "action": "next action item."

        Below is fist output example given original query:

        Original query: What is RoPE positional encoding.

        {{
            "rational": "No related content found for user .",
            "action": "query"
        }}

        Above is first output example given original query:


        Below is second output example given original query:

        Original query: What is the difference between RoPE positional encoding and absolute postional encoding.

        {{
            "rational": "Context is sufficient to answer user query.",
            "action": "context_sufficient"
        }}

        Above is second output example given original query:

        Below is user original query:
        {user_query}
        """

        # assemble conversation history
        history_conversation = []
        for i in range(len(self._chat_history) - 2, -1, -1):
            # ignore last message because it's user input query
            msg = self._chat_history[i].body
            if isinstance(msg, SystemMessage):
                # ignore system message cause it's knowledge in use.
                continue
            conversation = f"Role: {msg.source}\n\nContent:\n{msg.content}" + f"\n{'-' * 8}\n\n"
            history_conversation.append(conversation)
        idx = max_token_truncate(history_conversation, max_token_num=int(max_token_num * 0.8))
        history_conversation = history_conversation[:idx + 1]
        history_conversation.reverse()

        # get model result
        prompt = _parse_prompt.format(
            history_conversation="\n".join(history_conversation),
            user_query=message.body.content,
        )
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type} intent identify prompt:\n{pretty_format(prompt, indent=1)}')

        completion = await self._model_client.create(
            [SystemMessage(content=prompt)],
            cancellation_token=ctx.cancellation_token,
        )
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: completion response:\n{pretty_format(completion, indent=1)}')

        reduced_completion_content = re.sub(r"<think>[.\S\s]*</think>", "", completion.content).strip()
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: reduced query response:\n{pretty_format(reduced_completion_content, indent=1)}')

        # next action
        parse_result = json.loads(reduced_completion_content)
        query_parse_result = QueryParseResult(
            rational=parse_result.get('rational', None),
            action=parse_result.get('action', None),
            original_query=message.body.content,
        )

        if query_parse_result.action == 'context_sufficient':
            logging.info(f'{self.id.type}:' + '-' * 80)
            logging.info(f'{self.id.type}: model thinks context is sufficient, trigger answer generation')
            await self.publish_message(
                message=GenerationRequest(),
                topic_id=DefaultTopicId(type=self._chat_topic_type),
            )
            return
        elif query_parse_result.action == 'query':
            await self.publish_message(
                message=query_parse_result,
                topic_id=DefaultTopicId(type=self._query_rewriter_topic_type),
            )

        else:
            raise Exception(f"{self.id.type}: invalid action: {query_parse_result.action}")


# ------------------------------------------------------------------------------
# Query rewriter agent
class QueryRewriterAgent(RoutedAgent):
    """Agent for rewriting user input query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        num_queries: int,
        search_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._model_client = model_client
        self._user_query_history: List[LLMMessage] = []
        self._num_queries = num_queries
        self._search_topic_type = search_topic_type

    @message_handler
    async def handle_chat_message(self, message: ChatMessage, ctx: MessageContext) -> None:
        if isinstance(message.body, UserMessage):
            # rewriter only considers user messages
            logging.info(f'{self.id.type}:' + '-' * 80)
            logging.info(f'{self.id.type}: append user chat message:\n{pretty_format(message, indent=1)}')
            self._user_query_history.append(message)

    @message_handler
    async def handle_query_parse_result_message(self, message: QueryParseResult, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: handle query rewrite message:\n{pretty_format(message, indent=1)}')

        _query_rewrite_prompt = """
        You are a search assistant. Your goal is to generate sophisticated and diverse search queries.
        These queries are intended for an advanced automated research tool capable of analyzing complex results, expand topics based on user query and synthesizing information.

        Below is history user queries:

        {history_queries}

        Above is history user queries.


        Instructions:
        - Always prefer a single search query, only add another query if the original question requests multiple aspects or elements and one query is not enough.
        - Each query should focus on one specific aspect of the original question.
        - Don't produce more than {num_queries} queries.
        - Queries should be diverse, if the topic is broad, generate more than 1 query.
        - Don't generate multiple similar queries, one is enough.

        Format:
        - Format your response as a JSON object with ALL two of these exact keys:
        - "rational": Brief explanation of why these queries are relevant
        - "query": A list of search queries


        Below is one output example given original query:

        Original query: What revenue grew more last year apple stock or the number of people buying an iphone

        {{
            "rational": "To answer this comparative growth question accurately, we need specific data points on Apple's stock performance and iPhone sales metrics. These queries target the precise financial information needed: company revenue trends, product-specific unit sales figures, and stock price movement over the same fiscal period for direct comparison.",
            "query": ["Apple total revenue growth fiscal year 2024", "iPhone unit sales growth fiscal year 2024", "Apple stock price growth fiscal year 2024"],
        }}

        Above is one output example given original query.


        Below is the original query:

        {original_query}

        Above is the original query.
        """
        
        # format history queries
        history_queries = []
        for i in range(len(self._user_query_history) - 2, -1, -1):
            # ignore latest message because it's the query to be rewritted
            msg = self._user_query_history[i]
            if not isinstance(msg.body, UserMessage):
                continue

            query = f"Query: {msg.body.content}\n" + f"{'-' * 8}\n"
            history_queries.append(query)
        idx = max_token_truncate(history_queries, max_token_num=int(max_token_num * 0.8))
        history_queries = history_queries[:idx + 1]
        history_queries.reverse()

        # get model result
        prompt = _query_rewrite_prompt.format(
            num_queries=self._num_queries,
            original_query=message.original_query,
            history_queries='\n'.join(history_queries),
        )
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: query rewrite prompt:\n{pretty_format(prompt, indent=1)}')

        completion = await self._model_client.create([SystemMessage(content=prompt)], cancellation_token=ctx.cancellation_token)
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: completion response:\n{pretty_format(completion, indent=1)}')

        reduced_completion_content = re.sub(r'<think>[.\s\S]*</think>', '', completion.content)
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: reduced comletion content:\n{pretty_format(reduced_completion_content, indent=1)}')

        query = json.loads(reduced_completion_content)
        search_request = SearchRequest(query=query.get('query', []))

        # publish query rewrite result
        await self.publish_message(
            message=search_request,
            topic_id=DefaultTopicId(type=self._search_topic_type),
        )


# ------------------------------------------------------------------------------
# knowledge base search agent
class SearchAgent(RoutedAgent):
    """Agent that searches knowledge base using query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        search_server_url: str,
        search_config: Dict[str, Any],
        chat_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._description = description
        self._model_client = model_client
        self._search_server_url = search_server_url
        self._search_config = search_config
        self._chat_topic_type = chat_topic_type

    def search(self, query: str) -> List[Chunk]:
        # get search result
        response = requests.post(
            url=self._search_server_url,
            json={
                'query': {
                    'question': query,
                },
                'config': self._search_config,
            },
            stream=False,
        )
        response.raise_for_status()

        # parse chunk
        content = json.loads(response.text)
        chunks = []
        for dataload in content['data']:
            chunk = Chunk(
                content_type=ChunkType(dataload.get('content_type', None)),
                file_name=dataload.get('file_name', None),
                content_url=dataload.get('content_url', None),
                content=dataload.get('content', ''.encode('utf-8')).encode('utf-8', errors='ignore'),
                extra_description=dataload.get('extra_description', ''.encode('utf-8')).encode('utf-8', errors='ignore'),
            )
            # NOTE: set uuid instead of auto generating
            chunk.uuid = dataload.get('uuid', None)
            chunks.append(chunk)

        return chunks

    @message_handler
    async def handle_search_message(self, message: SearchRequest, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: handle search request:\n{pretty_format(message, indent=1)}')

        all_chunks = []
        for query in message.query:
            ret = self.search(query=query)
            all_chunks.extend(ret)

        # assemble knowledge base
        knowledge_base, refid2meta = assemble_knowledge_base(all_chunks)
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: knowledge base:\n{pretty_format(knowledge_base, indent=1)}')
        logging.info(f'{self.id.type}: reference meta:\n{pretty_format(refid2meta, indent=1)}')

        # publish system knowledge base update message
        await self.publish_message(
            message=ChatMessage(body=SystemMessage(content=knowledge_base), meta=refid2meta),
            topic_id=DefaultTopicId(type=self._chat_topic_type),
        )

        # trigger LLM answer generation
        await self.publish_message(
            message=GenerationRequest(),
            topic_id=DefaultTopicId(type=self._chat_topic_type),
        )


# ------------------------------------------------------------------------------
# Response generation
class GeneratorAgent(RoutedAgent):
    """Agent that generates answer using system knowledge and history messages."""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        chat_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._description = description
        self._model_client = model_client
        self._chat_topic_type = chat_topic_type
        self._chat_history: List[LLMMessage] = []

    @message_handler
    async def handle_chat_message(self, message: ChatMessage, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type} handle chat message:\n{pretty_format(message, indent=1)}')

        # update system knowledge message
        if isinstance(message.body, SystemMessage):
            if len(self._chat_history) > 0 and isinstance(self._chat_history[0].body, SystemMessage):
                # update system messages
                self._chat_history[0] = message
            else:
                # insert new system message
                self._chat_history.insert(0, message)
            return

        # append agent message / user message
        self._chat_history.append(message)

    @message_handler
    async def handle_generation_request(self, message: GenerationRequest, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type} handle generation request:\n{pretty_format(message, indent=1)}')

        from rag.prompt import prompt_system, promot_citation

        # assemble knwoledge base and history
        knowledge_base_msg = None
        for msg in self._chat_history:
            if isinstance(msg.body, SystemMessage):
                knowledge_base_msg = msg
                break

        knowledge_base = knowledge_base_msg.body.content
        refid2meta = knowledge_base_msg.meta
        knowledge_base_prompt= prompt_system.format(knowledge_base=knowledge_base) \
                            + f"\n{'-' * 8}\n" \
                            + promot_citation

        logging.info(f'{self.id.type}:' + '-' * 80)
        logging.info(f'{self.id.type}: knowledge base prompt:\n{pretty_format(knowledge_base_prompt, indent=1)}')
        logging.info(f'{self.id.type}: reference meta:\n{pretty_format(refid2meta, indent=1)}')

        # assemble history conversations
        conversations = []
        conversation_content = []
        for i in range(len(self._chat_history) - 1, -1, -1):
            msg: ChatMessage = self._chat_history[i]
            if isinstance(msg.body, SystemMessage):
                continue
            conversations.append(msg.body)
            conversation_content.append(msg.body.content)

        idx = max_token_truncate(conversation_content, int(0.6 * max_token_num))
        conversations = conversations[:idx + 1]
        conversations.reverse()

        # get model response
        completion = await self._model_client.create(
            [SystemMessage(content=knowledge_base_prompt)] + conversations,
            cancellation_token=ctx.cancellation_token,
        )

        # print response
        # reset global generating flag
        global is_generating
        is_generating = False

        print('', end='\r', flush=True)
        Console().print(Markdown(_escape_markdown(completion.content)))

        # print reference
        from rag.llm import format_reference_info
        formatted_ref = format_reference_info(refid2meta, completion.content)
        logging.info(f'{self.id.type}: formatted reference data: {pretty_format(formatted_ref, indent=1)}')
        Console().print(Markdown(_escape_markdown(formatted_ref)))

        # publish assistance message
        await self.publish_message(
            message=ChatMessage(body=AssistantMessage(content=completion.content, source='Assistant')),
            topic_id=DefaultTopicId(type=self._chat_topic_type),
        )


# ------------------------------------------------------------------------------

_job_executor = None


def get_job_executor() -> ThreadPoolExecutor:
    """
    Get a job executor for print loading mark.
    """
    global _job_executor
    if _job_executor is None:
        # NOTE: set only 1 thread to force sequencial job schedule.
        _job_executor = ThreadPoolExecutor(max_workers=1)

    return _job_executor


def parse_user_instruct(user_input: str) -> None | str:
    user_input = user_input.strip()
    if len(user_input) == 0:
        return

    if user_input.lower() in ['?', '/help', '/h']:
        print("""Help info:
/help: show help info.
/exit: exit and save conversation as json.
""")
    elif user_input == '/exit':
        print('byte:)')
        os._exit(0)

    else:
        return user_input.strip()


def print_loading_mark() -> None:
    global is_generating

    loading_mark = ['-', '\\', '|', '/']
    idx = 0
    while True:
        if is_generating:
            ch = loading_mark[idx % len(loading_mark)]
            idx = (idx + 1) % len(loading_mark)
            print(ch, end='\r', flush=True)

        time.sleep(0.05)


async def main():
    # NOTE: re-init root logger
    import utils
    utils.initialized_root_logger = False
    from utils import init_root_logger
    init_root_logger('agent_run', need_stream=False)

    global is_generating
    is_generating = False
    job_executor = get_job_executor()
    job_executor.submit(print_loading_mark)

    # register agents
    runtime = SingleThreadedAgentRuntime()

    # topics and agent description
    chat_topic_type = 'group_chat'
    query_master_desc = "Query master for prediction next action on user input"

    query_rewriter_topic_type = 'query_rewriter'
    query_rewriter_desc = 'Rewrite user query'

    search_topic_type = 'query_search'
    search_desc = 'Search knowledge base and return result'

    generator_desc = 'Answer generator'

    # query master
    query_master_type = await QueryMasterAgent.register(
        runtime,
        'query_master',
        lambda: QueryMasterAgent(
            model_client=model_client,
            description=query_master_desc,
            query_rewriter_topic_type=query_rewriter_topic_type,
            chat_topic_type=chat_topic_type,
        ),
    )
    # listen to `chat_topic_type`
    await runtime.add_subscription(TypeSubscription(topic_type=chat_topic_type, agent_type=query_master_type.type))

    # query rewriter
    query_rewriter_type = await QueryRewriterAgent.register(
        runtime,
        query_rewriter_topic_type,  # topic type as agent type
        lambda: QueryRewriterAgent(
            model_client=model_client,
            description=query_rewriter_desc,
            num_queries=4,
            search_topic_type=search_topic_type,
        ),
    )
    # listen to `chat_topic_type` and `query_rewriter_topic_type`
    await runtime.add_subscription(TypeSubscription(topic_type=chat_topic_type, agent_type=query_rewriter_type.type))
    await runtime.add_subscription(TypeSubscription(topic_type=query_rewriter_topic_type, agent_type=query_rewriter_type.type))

    # search agent
    search_type = await SearchAgent.register(
        runtime,
        search_topic_type,  # topic type as agent type
        lambda: SearchAgent(
            model_client=model_client,
            description=search_desc,
            search_server_url=search_host,
            search_config={'limit': 4},
            chat_topic_type=chat_topic_type,
        ),
    )
    # listen to search_topic_type topic
    await runtime.add_subscription(TypeSubscription(topic_type=search_topic_type, agent_type=search_type.type))

    # generator agent
    generator_type = await GeneratorAgent.register(
        runtime,
        'generator_agent',
        lambda: GeneratorAgent(
            model_client=model_client,
            description=generator_desc,
            chat_topic_type=chat_topic_type,
        ),
    )
    # listen to `chat_topic_type`.
    await runtime.add_subscription(TypeSubscription(topic_type=chat_topic_type, agent_type=generator_type.type))

    # start the conversation
    Console().print(Markdown('-' * 4))

    input_placeholder = 'type <esc> then <enter> to finish'
    runtime.start()
    session_id = str(uuid.uuid4())
    session = PromptSession()
    while True:
        try:
            # get user input
            user_input = await session.prompt_async(">>", multiline=True, placeholder=input_placeholder)
            user_input = parse_user_instruct(user_input=user_input)
            logging.info(f'begin to process user input: {user_input}')

            is_generating = True
            await runtime.publish_message(
                ChatMessage(
                    body=UserMessage(content=user_input, source="User"),
                    meta=None,
                ),
                TopicId(type=chat_topic_type, source=session_id),
            )
            while is_generating:
                await asyncio.sleep(0.5)

            Console().print(Markdown('-' * 4))

        except KeyboardInterrupt:
            os._exit(0)
        except EOFError:
            os._exit(0)


import asyncio

asyncio.run(main())
