import json
import string
import uuid
import logging
import re
from typing import List, Dict, Any, Optional

import requests

import openai
from pydantic import BaseModel
from autogen_core import (
    DefaultTopicId,
    MessageContext,
    RoutedAgent,
    SingleThreadedAgentRuntime,
    TopicId,
    TypeSubscription,
    message_handler,
)

from autogen_core.models import (
    ChatCompletionClient,
    LLMMessage,
    SystemMessage,
    UserMessage,
    AssistantMessage,
)

from autogen_ext.models.ollama import OllamaChatCompletionClient

model_client = OllamaChatCompletionClient(model='qwen3:30b-a3b', host='http://127.0.0.1:11434')

from rag.llm import max_token_truncate, assemble_knowledge_base
from parse.parser import Chunk, ChunkType

max_token_num = 80 * 1024

# ------------------------------------------------------------------------------
# Messages


class GroupChatMessage(BaseModel):
    """
    Group chat messages, generated by `user` / `system` / `assistance`.
    """
    body: LLMMessage
    meta: Optional[Dict[Any, Any]] = None  # extra meta data.


class QueryParseResult(BaseModel):
    rational: str  # Breif explaination why the action is determined.
    action: str  # Action
    original_query: str  # User original query


class SearchRequest(BaseModel):
    query: List[str]  # list of queries to execute


# ------------------------------------------------------------------------------
# Agents
# Query master
class QueryMasterAgent(RoutedAgent):
    """Agent that parses user input query and recognize user intent"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        query_rewriter_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._model_client = model_client
        self._chat_history: List[LLMMessage] = []
        self._query_rewriter_topic_type = query_rewriter_topic_type

    @message_handler
    async def handle_group_chat_message(self, message: GroupChatMessage, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type} handle group chat message, message content:\n{message.body}')

        if isinstance(message.body, SystemMessage):
            if len(self._chat_history) > 0 and isinstance(self._chat_history[0].body, SystemMessage):
                # update system messages
                self._chat_history[0] = message
            else:
                # insert new system message
                self._chat_history.insert(0, message)
            return

        if isinstance(message.body, AssistantMessage):
            # append message but donot trigger query parsing.
            self._chat_history.append(message)
            return

        self._chat_history.append(message)

        _parse_prompt = """You are a query understanding agent in a research conversation and working with other agents. Your role is to parse user query and determine what to do next given conversation history.

Below is history conversations:

{history_conversation}

Above is history conversations.

Instructions:
- User query may not necessary trigger query action when history information is sufficient. In this case you can just return 'context_sufficient'.
- If current context is not sufficient to answer user question, you need to return `query`.


Format:
- Format your response as a JSON object with ALL two of these exact keys:
    - "rational": "Brief explanation of why the action is necessary.",
    - "action": "next action item."

Below is fist output example given original query:

Original query: What is RoPE positional encoding.

{{
    "rational": "No related content found for user .",
    "action": "query"
}}

Above is first output example given original query:


Below is second output example given original query:

Original query: What is the difference between RoPE positional encoding and absolute postional encoding.

{{
    "rational": "Context is sufficient to answer user query.",
    "action": "context_sufficient"
}}

Above is second output example given original query:

Below is user original query:
{user_query}
"""

        # format history conversation
        history_conversation = []
        for i in range(len(self._chat_history) - 2, -1, -1):
            # ignore last message because it's user input query
            msg = self._chat_history[i].body
            if isinstance(msg, SystemMessage):
                # ignore system message cause it's knowledge in use.
                continue
            conversation = f"Role: {msg.source}\nContent:\n{msg.content}" + f"\n{'-' * 8}\n"
            history_conversation.append(conversation)
        idx = max_token_truncate(history_conversation, max_token_num=int(max_token_num * 0.8))
        history_conversation = history_conversation[:idx + 1]
        history_conversation.reverse()

        # get model result
        prompt = _parse_prompt.format(
            history_conversation="\n".join(history_conversation),
            user_query=message.body.content,
        )
        completion = await self._model_client.create(
            [SystemMessage(content=prompt)],
            cancellation_token=ctx.cancellation_token,
        )
        logging.info(f'{self.id.type}: query response:\n{completion.content}')
        reduced_completion_content = re.sub(r"<think>[.\S\s]*</think>", "", completion.content).strip()
        logging.info(f'{self.id.type}: reduced query response:\n{reduced_completion_content}')

        # next action
        parse_result = json.loads(reduced_completion_content)
        query_parse_result = QueryParseResult(
            rational=parse_result.get('rational', None),
            action=parse_result.get('action', None),
            original_query=message.body.content,
        )

        if query_parse_result.action == 'context_sufficient':
            logging.info(f'{self.id.type}: model thinks context is sufficient, continue')
            return
        elif query_parse_result.action == 'query':
            await self.publish_message(
                message=query_parse_result,
                topic_id=DefaultTopicId(type=self._query_rewriter_topic_type),
            )

        else:
            raise Exception(f"{self.id.type}: invalid action: {query_parse_result.action}")


# ------------------------------------------------------------------------------
# Query rewriter agent
class QueryRewriterAgent(RoutedAgent):
    """Agent for rewriting user input query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        num_queries: int,
        search_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._model_client = model_client
        self._user_query_history: List[LLMMessage] = []
        self._num_queries = num_queries
        self._search_topic_type = search_topic_type

    @message_handler
    async def handle_group_chat_message(self, message: GroupChatMessage, ctx: MessageContext) -> None:
        if isinstance(message.body, UserMessage):
            # rewriter only care user messages
            logging.info(f'{self.id.type}: append group chat user message:\n{message.body}')
            self._user_query_history.append(message)

    @message_handler
    async def handle_query_parse_result_message(self, message: QueryParseResult, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}: handle query rewrite message:\n{message}')

        _query_rewrite_prompt = """
You are a search assistant. Your goal is to generate sophisticated and diverse search queries. These queries are intended for an advanced automated research tool capable of analyzing complex results, expand topics based on user query and synthesizing information.

Below is history user queries:

{history_queries}

Above is history user queries.


Instructions:
- Always prefer a single search query, only add another query if the original question requests multiple aspects or elements and one query is not enough.
- Each query should focus on one specific aspect of the original question.
- Don't produce more than {num_queries} queries.
- Queries should be diverse, if the topic is broad, generate more than 1 query.
- Don't generate multiple similar queries, one is enough.

Format:
- Format your response as a JSON object with ALL two of these exact keys:
   - "rational": Brief explanation of why these queries are relevant
   - "query": A list of search queries


Below is one output example given original query:

Original query: What revenue grew more last year apple stock or the number of people buying an iphone

{{
    "rational": "To answer this comparative growth question accurately, we need specific data points on Apple's stock performance and iPhone sales metrics. These queries target the precise financial information needed: company revenue trends, product-specific unit sales figures, and stock price movement over the same fiscal period for direct comparison.",
    "query": ["Apple total revenue growth fiscal year 2024", "iPhone unit sales growth fiscal year 2024", "Apple stock price growth fiscal year 2024"],
}}

Above is one output example given original query.


Below is the original query:

{original_query}

Above is the original query.
"""
        # format history queries
        history_queries = []
        for i in range(len(self._user_query_history) - 2, -1, -1):
            # ignore latest message because it's the query to be rewritted
            msg = self._user_query_history[i]
            if not isinstance(msg.body, UserMessage):
                continue

            query = f"Query: {msg.body.content}\n" + f"{'-' * 8}\n"
            history_queries.append(query)
        idx = max_token_truncate(history_queries, max_token_num=int(max_token_num * 0.8))
        history_queries = history_queries[:idx + 1]
        history_queries.reverse()

        # get model result
        prompt = _query_rewrite_prompt.format(
            num_queries=self._num_queries,
            original_query=message.original_query,
            history_queries='\n'.join(history_queries),
        )
        logging.info(f'{self.id.type}: system prompt:\n{prompt}')
        completion = await self._model_client.create([SystemMessage(content=prompt)], cancellation_token=ctx.cancellation_token)
        logging.info(f'{self.id.type}: rewrite query response:\n{completion.content}')

        reduced_completion_content = re.sub(r'<think>[.\s\S]*</think>', '', completion.content)
        logging.info(f'{self.id.type}: reduced comletion content:\n{reduced_completion_content}')

        query = json.loads(reduced_completion_content)
        query_msg = SearchRequest(query=query.get('query', []))

        # publish query rewrite result
        await self.publish_message(
            message=query_msg,
            topic_id=DefaultTopicId(type=self._search_topic_type),
        )


# ------------------------------------------------------------------------------
# knowledge base search agent
class SearchAgent(RoutedAgent):
    """Agent handling user input query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        search_server_url: str,
        search_config: Dict[str, Any],
        group_chat_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._description = description
        self._model_client = model_client
        self._search_server_url = search_server_url
        self._search_config = search_config
        self._group_chat_topic_type = group_chat_topic_type

    def search(self, query: str) -> List[Chunk]:
        # get search result
        response = requests.post(
            url=self._search_server_url,
            json={
                'query': {
                    'question': query,
                },
                'config': self._search_config,
            },
            stream=False,
        )
        response.raise_for_status()

        # parse chunk
        content = json.loads(response.text)
        chunks = []
        for dataload in content['data']:
            chunk = Chunk(
                content_type=ChunkType(dataload.get('content_type', None)),
                file_name=dataload.get('file_name', None),
                content_url=dataload.get('content_url', None),
                content=dataload.get('content', bytes('', encoding='utf-8')).encode('utf-8', errors='ignore'),
                extra_description=dataload.get('extra_description', bytes('', encoding='utf-8')).encode('utf-8', errors='ignore'),
            )
            # NOTE: set uuid instead of auto generating
            chunk.uuid = dataload.get('uuid', None)
            chunks.append(chunk)

        return chunks

    @message_handler
    async def handle_search_message(self, message: SearchRequest, ctx: MessageContext) -> None:
        logging.info(f'{self.id.type}: handle search request:\n{message}')

        all_chunks = []
        for query in message.query:
            ret = self.search(query=query)
            all_chunks.extend(ret)

        # assemble knowledge base
        knowledge_base, refid2meta = assemble_knowledge_base(all_chunks)
        logging.info(f'{self.id.type}: knowledge base:\n{knowledge_base}')
        logging.info(f'{self.id.type}: reference meta:\n{json.dumps(refid2meta, indent=4)}')

        # publish system knowledge base update message
        await self.publish_message(
            message=GroupChatMessage(body=SystemMessage(content=knowledge_base), meta=refid2meta),
            topic_id=DefaultTopicId(type=self._group_chat_topic_type),
        )

        # TODO: trigger LLM answer generation


# ------------------------------------------------------------------------------
async def main():
    from utils import init_root_logger
    init_root_logger('agent_run')

    runtime = SingleThreadedAgentRuntime()

    # topic type as agent type
    group_chat_topic_type = 'group_chat'
    query_master_desc = "Query parser for parsing user query input"

    query_rewriter_topic_type = 'query_rewriter'
    query_rewriter_desc = 'Rewrite user query'

    search_topic_type = 'query_search'
    search_desc = 'search knowledge base and return result'

    system_knowledge_topic_type = 'system_knowledge'
    system_knowledge_desc = 'system_knowledge'

    # query master
    query_master_type = await QueryMasterAgent.register(
        runtime,
        group_chat_topic_type,  # topic type as agent type
        lambda: QueryMasterAgent(
            model_client=model_client,
            description=query_master_desc,
            query_rewriter_topic_type=query_rewriter_topic_type,
        ),
    )
    # listen to `group_chat_topic_type`
    await runtime.add_subscription(TypeSubscription(topic_type=group_chat_topic_type, agent_type=query_master_type.type))

    # query rewriter
    query_rewriter_type = await QueryRewriterAgent.register(
        runtime,
        query_rewriter_topic_type,  # topic type as agent type
        lambda: QueryRewriterAgent(
            model_client=model_client,
            description=query_rewriter_desc,
            num_queries=4,
            search_topic_type=search_topic_type,
        ),
    )
    # listen to `group_chat_topic_type` and `query_rewriter_topic_type`
    await runtime.add_subscription(TypeSubscription(topic_type=group_chat_topic_type, agent_type=query_rewriter_type.type))
    await runtime.add_subscription(TypeSubscription(topic_type=query_rewriter_topic_type, agent_type=query_rewriter_type.type))

    # search agent
    search_type = await SearchAgent.register(
        runtime,
        search_topic_type,  # topic type as agent type
        lambda: SearchAgent(
            model_client=model_client,
            description=query_rewriter_desc,
            search_server_url="http://127.0.0.1:4567/search",
            search_config={'limit': 2},
            group_chat_topic_type=group_chat_topic_type,
        ),
    )
    # listen to search_topic_type topic
    await runtime.add_subscription(TypeSubscription(topic_type=search_topic_type, agent_type=search_type.type))

    # start the conversation
    runtime.start()
    session_id = str(uuid.uuid4())
    await runtime.publish_message(
        GroupChatMessage(
            body=UserMessage(content="what is large language model ?", source="User"),
            meta=None,
        ),
        TopicId(type=group_chat_topic_type, source=session_id),
    )
    await runtime.stop_when_idle()
    await model_client.close()


import asyncio

asyncio.run(main())
