root_data_dir: /var/data/tiny_rag
search_service_port: 4500
search_service_url: http://localhost:4500
ollama_host: http://127.0.0.1:11434
ollama_model: qwen3:30b-a3b-thinking-2507-q4_K_M
vision_model: qwen2.5vl:7b
max_context_token_num: 30000
host_file_dir: /Users/xcoder/obsidian/Profession
ignore_path_patterns:
    - "daily notes"
    - node_modules
    - attachments
    - .obsidian
    - .git
    - .DS_Store
    - .Trash
    - .vscode
    - .idea
support_file_types:
    - md
    - txt
    - text
    - png
    - jpg
    - jpeg
    - bmp
    - gif

parser_config:
    config_file_path: /Users/xcoder/projects/tiny_rag/assets/MinerU/magic-pdf.json
    asset_save_dir: /Users/xcoder/obsidian/Profession/attachments

embedding_config:
    embedding_model_name: dengcao/Qwen3-Embedding-4B:Q5_K_M
    embedding_dim: 2560
    embedding_support_sparse_vector: false
    embedding_model_dir: /Users/xcoder/.cache/huggingface/hub/models--Qwen--Qwen3-Embedding-4B/snapshots/5cf2132abc99cad020ac570b19d031efec650f2b

gen_conf:
    temperature: 0.7
    top_p: 0.4
    repeat_penalty: 1.2
    num_ctx: 30000

chunking_config:
    consecutive_block_num: 12
    block_overlap_num: 6
    consecutive_byte_num: 1000
    byte_overlap_num: 500

rational_db_config:
    db_name: /var/data/tiny_rag/rational_db/tiny_rag_rational.db

vector_db_config:
    db_name: /var/data/tiny_rag/vector_db/tiny_rag_vector.db
    embedding_column_name: embedding
    
object_store_config:
    conn_url: minio:6100
    user: minioadmin
    token: minioadmin

cache_config:
    conn_url: redis://localhost:23456/0
    token: ""
    key_ttl_seconds: 8640000
