services:
  minio:
    image: minio/minio:latest
    container_name: tiny_rag_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - tiny_rag_minio_data:/data
    networks:
      - tiny_rag
    

volumes:
  # container data persisted by local docker engine.
  tiny_rag_data:
    driver: local
  tiny_rag_minio_data:
    driver: local

networks:
  tiny_rag:
    driver: bridge
