services:
  tiny_rag:
    image: ${IMAGE}
    container_name: tiny_rag_server
    ports:
      # - ${SVR_HTTP_PORT}:9380
      - 4000:4000
    volumes:
      - ${HOST_RAG_LOG_DIR:-./docker/tiny_rag_logs}:/tiny_rag/logs
      - ${HOST_RAG_FILE_DIR:-./docker/files}:${RAG_FILE_DIR:-/var/share/tiny_rag_files} 
      - tiny_rag_data:${RAG_DATA_DIR:-/var/share/tiny_rag_data}
    env_file: env
    environment:
      - TZ=${TIMEZONE}
    networks:
      - tiny_rag
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  

volumes:
  # container data persisted by local docker engine.
  tiny_rag_data:
    driver: local

networks:
  tiny_rag:
    driver: bridge