services:
  minio:
    image: minio/minio:latest
    container_name: tiny_rag_minio
    ports:
      - "6100:6100"
      - "6101:6101"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address ":6100" --console-address ":6101"
    volumes:
      - tiny_rag_minio_data:/data
    networks:
      - tiny_rag

  redis:
    image: redis:latest
    container_name: tiny_rag_redis
    ports:
      - "23456:23456"
    volumes:
      - tiny_rag_redis_data:/data
    networks:
      - tiny_rag
    command: redis-server --port 23456

  tiny_rag:
    image: tiny_rag:dev
    container_name: tiny_rag
    ports:
      - "4500:4500"
    environment:
      - TINY_RAG@@search_service_port=4500
      - TINY_RAG@@cache_config@@conn_url=redis://redis:23456/0
      - TINY_RAG@@object_store_config@@conn_url=minio:6100
      - TINY_RAG@@object_store_config@@user=minioadmin
      - TINY_RAG@@object_store_config@@token=minioadmin
    volumes:
      - tiny_rag_data:/var/data/tiny_rag
    depends_on:
      - minio
      - redis
    networks:
      - tiny_rag
    
volumes:
  tiny_rag_data:
    driver: local
  tiny_rag_minio_data:
    driver: local
  tiny_rag_redis_data:
    driver: local

networks:
  tiny_rag:
    driver: bridge
