services:
  redis:
    image: valkey/valkey:8
    container_name: tiny_rag_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - tiny_rag_redis_data:/data
    networks:
      - tiny_rag
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: on-failure
    

volumes:
  tiny_rag_redis_data:
    driver: local
  tiny_rag_etcd_data:
    driver: local
  tiny_rag_minio_data:
    driver: local
  tiny_rag_milvus_data:
    driver: local


networks:
  tiny_rag:
    driver: bridge
