include:
  - ./docker-compose-base.yml

services:
  tiny_rag:
    # depends_on:
    #   redis:
    #     condition: service_healthy
    image: tiny_rag:dev
    container_name: tiny_rag_server
    ports:
      # - ${SVR_HTTP_PORT}:9380
      # - 80:80
      # - 443:443
      - 4000:4000
      - 4567:4567
    volumes:
      - ./tiny_rag_logs:/tiny_rag/logs
      - ${HOST_RAG_FILE_DIR:-./files}:${RAG_FILE_DIR:-/var/share/tiny_rag_files} 
      - tiny_rag_data:${RAG_DATA_DIR:-/var/share/tiny_rag_data}
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS:-1}
      - LIGHTEN=${LIGHTEN:-1}
    networks:
      - tiny_rag
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  

volumes:
  tiny_rag_data:
    driver: local