# services:
#   redis:
#     image: valkey/valkey:8
#     container_name: tiny_rag_redis
#     command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
#     env_file: .env
#     ports:
#       - ${REDIS_PORT}:6379
#     volumes:
#       - tiny_rag_redis_data:/data
#     networks:
#       - tiny_rag
#     healthcheck:
#       test: ["CMD", "redis-cli","ping"]
#       interval: 5s
#       timeout: 5s
#       retries: 3
#     restart: on-failure
    

networks:
  tiny_rag:
    driver: bridge
