import asyncio
import json
import logging
import os
import re
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from typing import Any

import json_repair
from autogen_core import (
    DefaultTopicId,
    MessageContext,
    RoutedAgent,
    SingleThreadedAgentRuntime,
    TopicId,
    TypeSubscription,
    message_handler,
)
from autogen_core.models import (
    AssistantMessage,
    ChatCompletionClient,
    CreateResult,
    SystemMessage,
    UserMessage,
)
from autogen_ext.models.ollama import OllamaChatCompletionClient
from prompt_toolkit import PromptSession
from pydantic import BaseModel, Field
from rich.console import Console
from rich.markdown import Markdown

from common.config import TinyRAGConfig
from common.data import Chunk, ContentType
from common.logger import get_logger
from common.utils import estimate_token_num
from rag.functions import search
from rag.llm import assemble_knowledge_base
from rag.prompt import PROMPT_QUERY_REWRITE, PROMPT_RERANK

# global args
MAX_TOKEN_NUM = 32 * 1024
is_generating = False
QUERY_REWRITE_NUM = 3
SEARCH_LIMIT = 5

Logger = get_logger("agent_search", need_stream=False)
# ------------------------------------------------------------------------------
# Util funcs


def _escape_markdown(text: str) -> str:
    if text is None:
        return text

    text = re.sub(r"<(.?)", r"&lt;\1", text)
    text = re.sub(r"(.?)>", r"\1&gt;", text)

    return text


def _max_token_truncate(history: list[str], max_token_num: int) -> int:
    """
    Truncate by max token num. Return index such that token num of history[:index + 1] <= max_token_num

    Args:
    - history: a list of string.
    - max_token_num: maximum token num.
    """
    total_token_num = 0
    index = 0
    for i, msg in enumerate(history):
        token_num, _ = estimate_token_num(msg)
        if total_token_num + token_num >= max_token_num:
            break
        else:
            index = i
    return index


_log_divider = "\n" + "*" * 120 + "\n"
# ------------------------------------------------------------------------------
# Messages


class ChatMessage(BaseModel):
    """
    Group chat messages, generated by `user` / `system` / `assistance`.
    """

    body: UserMessage | SystemMessage | AssistantMessage
    meta: dict[str, dict[str, Any]] | None = None  # extra meta data.


class QueryParseResult(BaseModel):
    original_query: str = Field("", description="just copy original query")


class QueryRewriteResult(BaseModel):
    rational: str = Field("", description="brief explanation of why these queries are relevant")
    query: list[str] = Field(default_factory=list, description="a list of search queries")


class SearchRequest(BaseModel):
    query: list[str] = Field(default_factory=list, description="parsed search queries")  # list of related result ids


class RerankResult(BaseModel):
    ids: list[str] = Field(default_factory=list, description="a list of related result ids")


class GenerationRequest(BaseModel):
    pass


# ------------------------------------------------------------------------------
# Agents


# Query rewriter agent
class QueryRewriterAgent(RoutedAgent):
    """Agent for rewriting user input query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        num_queries: int,
        search_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._model_client = model_client
        self._user_query_history: list[ChatMessage] = []
        self._num_queries = num_queries
        self._search_topic_type = search_topic_type

    @message_handler
    async def handle_query_parse_result_message(self, message: QueryParseResult, ctx: MessageContext) -> None:
        Logger.info(
            f"{_log_divider + self.id.type}: handle query rewrite message:\n{json.dumps(message.model_dump(), indent=4, ensure_ascii=False, default=str)}{_log_divider}"
        )
        # append user query message
        self._user_query_history.append(
            ChatMessage(
                body=UserMessage(content=message.original_query, source="User"),
                meta=None,
            )
        )

        # format history queries
        history_queries = []
        step_time = time.time()
        for i in range(len(self._user_query_history) - 2, -1, -1):
            msg = self._user_query_history[i]
            if not isinstance(msg.body, UserMessage):
                continue
            history_queries.append(f"----\nQuery:\n```text\n{msg.body.content}\n```\n----\n")
        idx = _max_token_truncate(history_queries, max_token_num=int(MAX_TOKEN_NUM * 0.2))
        history_queries = history_queries[: idx + 1]
        history_queries.reverse()

        # get model result
        prompt = PROMPT_QUERY_REWRITE.format(
            num_queries=self._num_queries,
            original_query=message.original_query,
            history_queries="\n".join(history_queries),
            json_schema=json.dumps(QueryRewriteResult.model_json_schema(), indent=2),
        )
        Logger.info(f"{_log_divider + self.id.type}: query rewrite prompt:\n{prompt}{_log_divider}")

        query_rewrite: QueryRewriteResult | None = None
        resp: CreateResult | None = None
        try:
            resp = await self._model_client.create(
                [SystemMessage(content=prompt)], cancellation_token=ctx.cancellation_token
            )
            reduced_resp_content = re.sub(r"<think>[.\s\S]*</think>", "", str(resp.content))
            Logger.info(
                f"{_log_divider + self.id.type}: reduced comletion content:\n{reduced_resp_content}{_log_divider}"
            )
            raw_dict = json_repair.loads(reduced_resp_content)
            query_rewrite = QueryRewriteResult.model_validate(raw_dict)
        except Exception as e:
            Logger.error(f"{_log_divider + self.id.type}: fail to parse query rewrite result: {resp}\nError:\n{e}")
            query_rewrite = QueryRewriteResult(rational="", query=[message.original_query])

        # publish query rewrite result
        await self.publish_message(
            message=SearchRequest(query=query_rewrite.query),
            topic_id=DefaultTopicId(type=self._search_topic_type),
        )

        Logger.info(
            f"{_log_divider + self.id.type}: query rewrite done, time elapsed: {time.time() - step_time:.2f} seconds"
        )


# ------------------------------------------------------------------------------
# knowledge base search agent
class SearchAgent(RoutedAgent):
    """Agent that searches knowledge base using query"""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        chat_topic_type: str,
        search_limit: int,
    ) -> None:
        super().__init__(description=description)
        self._description = description
        self._model_client = model_client
        self._chat_topic_type = chat_topic_type
        self._search_limit = search_limit

    async def search(self, query: str, limit: int = 3) -> list[Chunk]:
        response = search(
            query=query,
            prompt_name="query: ",
            limit=limit,
        )
        if response and response.chunks:
            return response.chunks
        return []

    async def rerank(self, query: str, chunks: list[Chunk]) -> list[Chunk]:
        search_results = []
        for i, chunk in enumerate(chunks):
            search_results.append(
                f"---\n"
                f"ID:{i}\n"
                "content:\n```text\n"
                f"{chunk.content if chunk.content_type == ContentType.TEXT else chunk.extra_description}"
                "\n```\n"
                "---"
            )
        query = PROMPT_RERANK.format(
            query=query,
            search_results="\n".join(search_results),
            json_schema=json.dumps(RerankResult.model_json_schema(), indent=2),
        )
        logging.info(f"{_log_divider + self.id.type} rerank prompt:\n{query}{_log_divider}")

        # get rank result
        resp: CreateResult | None = None
        rank_result: RerankResult | None = None
        try:
            resp = await self._model_client.create([SystemMessage(content=query)])
            Logger.info(
                f"{_log_divider + self.id.type} rerank completion response:\n"
                f"{json.dumps(resp.model_dump(), indent=4, ensure_ascii=False, default=str)}{_log_divider}"
            )
            # parse result
            reduced_resp_content = re.sub(r"<think>[.\s\S]*</think>", "", str(resp.content))
            Logger.info(
                f"{_log_divider + self.id.type} reduced comletion content:\n{reduced_resp_content}{_log_divider}"
            )
            raw_dict = json_repair.loads(reduced_resp_content)
            rank_result = RerankResult.model_validate(raw_dict)
        except Exception as e:
            Logger.error(f"{_log_divider + self.id.type}: fail to rerank search result: {resp}\nError:\n{e}")
            return []

        # filter chunks
        filtered_chunks = []
        try:
            Logger.info(f"{_log_divider + self.id.type} rerank result ids:\n{rank_result.ids}{_log_divider}")
            filtered_chunks = []
            for idx in rank_result.ids:
                idx = int(idx)
                if idx < 0 or idx >= len(chunks):
                    continue
                filtered_chunks.append(chunks[idx])
        except Exception as e:
            Logger.error(f"{_log_divider + self.id.type}: fail to filter chunks:\n{e}")

        return filtered_chunks

    @message_handler
    async def handle_search_message(self, message: SearchRequest, ctx: MessageContext) -> None:
        Logger.info(
            f"{_log_divider + self.id.type}:\nhandle search request:\n{json.dumps(message.model_dump(), indent=4, ensure_ascii=False, default=str)}{_log_divider}"
        )

        # search
        step_time = time.time()
        all_chunks = []
        for query in message.query:
            ret = await self.search(query=query, limit=self._search_limit)
            all_chunks.extend(ret)

        # rank result
        all_chunks = await self.rerank(query="; ".join(message.query), chunks=all_chunks)

        knowledge_base, refid2meta = assemble_knowledge_base(all_chunks)
        Logger.info(f"{_log_divider + self.id.type}:\nknowledge base:\n{knowledge_base}{_log_divider}")
        Logger.info(
            f"{_log_divider + self.id.type}:\nreference meta:\n{json.dumps(refid2meta, indent=4, ensure_ascii=False, default=str)}{_log_divider}"
        )

        # publish system knowledge base update message
        await self.publish_message(
            message=ChatMessage(body=SystemMessage(content=knowledge_base), meta=refid2meta),
            topic_id=DefaultTopicId(type=self._chat_topic_type),
        )

        # trigger answer display
        await self.publish_message(
            message=GenerationRequest(),
            topic_id=DefaultTopicId(type=self._chat_topic_type),
        )
        Logger.info(f"{_log_divider + self.id.type}: search done, time elapsed: {time.time() - step_time:.2f} seconds")


# ------------------------------------------------------------------------------
# Response generation agent
class GeneratorAgent(RoutedAgent):
    """Agent that generates answer using system knowledge and history messages."""

    def __init__(
        self,
        description: str,
        model_client: ChatCompletionClient,
        chat_topic_type: str,
    ) -> None:
        super().__init__(description=description)
        self._description = description
        self._model_client = model_client
        self._chat_topic_type = chat_topic_type
        self._chat_history: list[ChatMessage] = []

    @message_handler
    async def handle_chat_message(self, message: ChatMessage, ctx: MessageContext) -> None:
        Logger.info(
            f"{_log_divider + self.id.type} handle chat message:\n{json.dumps(message.model_dump(), indent=2, ensure_ascii=False, default=str)}{_log_divider}"
        )

        # update system knowledge message
        if isinstance(message.body, SystemMessage):
            if len(self._chat_history) > 0 and isinstance(self._chat_history[0].body, SystemMessage):
                # update system messages
                self._chat_history[0] = message
            else:
                # insert new system message
                self._chat_history.insert(0, message)
            return

        # append agent message / user message
        self._chat_history.append(message)

    @message_handler
    async def handle_generation_request(self, message: GenerationRequest, ctx: MessageContext) -> None:
        Logger.info(
            f"{_log_divider + self.id.type} handle generation request:\n{json.dumps(message.model_dump(), indent=4, ensure_ascii=False, default=str)}{_log_divider}"
        )
        step_time = time.time()
        # assemble knwoledge base and history
        knowledge_base_msg: ChatMessage | None = None
        knowledge_base = ""
        for msg in self._chat_history:
            if isinstance(msg.body, SystemMessage):
                knowledge_base_msg = msg
                break
        if knowledge_base_msg:
            knowledge_base = knowledge_base_msg.body.content
        if knowledge_base_msg and knowledge_base_msg.meta:
            refid2meta = knowledge_base_msg.meta

        # print response
        # reset global generating flag
        global is_generating
        is_generating = False
        console = Console()
        console.print(Markdown("**Answer:**"))
        console.print(Markdown(_escape_markdown(str(knowledge_base))))

        Logger.info(
            f"{_log_divider + self.id.type}: generation done, time elapsed: {time.time() - step_time:.2f} seconds"
        )
        print(">>", end="", flush=True)


# ------------------------------------------------------------------------------

_job_executor = None


def get_job_executor() -> ThreadPoolExecutor:
    """
    Get a job executor for print loading mark.
    """
    global _job_executor
    if _job_executor is None:
        # NOTE: set only 1 thread to force sequencial job schedule.
        _job_executor = ThreadPoolExecutor(max_workers=1)

    return _job_executor


def parse_user_instruct(user_input: str) -> None | str:
    user_input = user_input.strip()
    if len(user_input) == 0:
        return

    if user_input.lower() in ["?", "/help", "/h"]:
        print("""Help info:
/help: show help info.
/exit: exit and save conversation as json.
""")
    elif user_input == "/exit":
        print("byte:)")
        os._exit(0)

    else:
        return user_input.strip()


def print_loading_mark() -> None:
    global is_generating

    loading_mark = ["-", "\\", "|", "/"]
    idx = 0
    while True:
        if is_generating:
            ch = loading_mark[idx % len(loading_mark)]
            idx = (idx + 1) % len(loading_mark)
            print(ch, end="\r", flush=True)

        time.sleep(0.05)


async def main():
    # print loading mark
    global is_generating
    is_generating = False
    job_executor = get_job_executor()
    job_executor.submit(print_loading_mark)

    # register agents
    runtime = SingleThreadedAgentRuntime()

    # topics and agent description
    chat_topic_type = "group_chat"

    query_rewriter_topic_type = "query_rewriter"
    query_rewriter_desc = "Rewrite user query"
    # query_rewriter_model = "qwen3:4b-thinking-2507-q4_K_M"
    query_rewriter_model = "qwen3:30b-a3b-thinking-2507-q4_K_M"

    search_topic_type = "query_search"
    search_desc = "Search knowledge base and return result"
    # search_model = "qwen3:4b-thinking-2507-q4_K_M"
    search_model = "qwen3:30b-a3b-instruct-2507-q4_K_M"

    generator_desc = "Answer generator"
    generator_model = "qwen3:30b-a3b-thinking-2507-q4_K_M"

    # query rewriter agent
    query_rewriter_type = await QueryRewriterAgent.register(
        runtime,
        query_rewriter_topic_type,  # topic type as agent type
        lambda: QueryRewriterAgent(
            model_client=OllamaChatCompletionClient(model=query_rewriter_model, **TinyRAGConfig.gen_conf.model_dump()),
            description=query_rewriter_desc,
            num_queries=QUERY_REWRITE_NUM,
            search_topic_type=search_topic_type,
        ),
    )
    await runtime.add_subscription(TypeSubscription(topic_type=chat_topic_type, agent_type=query_rewriter_type.type))
    await runtime.add_subscription(
        TypeSubscription(topic_type=query_rewriter_topic_type, agent_type=query_rewriter_type.type)
    )

    # search agent
    search_type = await SearchAgent.register(
        runtime,
        search_topic_type,  # topic type as agent type
        lambda: SearchAgent(
            model_client=OllamaChatCompletionClient(model=search_model, **TinyRAGConfig.gen_conf.model_dump()),
            description=search_desc,
            chat_topic_type=chat_topic_type,
            search_limit=SEARCH_LIMIT,
        ),
    )
    await runtime.add_subscription(TypeSubscription(topic_type=search_topic_type, agent_type=search_type.type))

    # generator agent
    generator_type = await GeneratorAgent.register(
        runtime,
        "generator_agent",
        lambda: GeneratorAgent(
            model_client=OllamaChatCompletionClient(model=generator_model, **TinyRAGConfig.gen_conf.model_dump()),
            description=generator_desc,
            chat_topic_type=chat_topic_type,
        ),
    )
    await runtime.add_subscription(TypeSubscription(topic_type=chat_topic_type, agent_type=generator_type.type))

    # start the conversation
    Console().print(Markdown("-" * 4))

    input_placeholder = "type <esc> then <enter> to finish"
    runtime.start()
    session_id = str(uuid.uuid4())
    session = PromptSession()
    while True:
        try:
            # get user input
            user_input = await session.prompt_async(">>", multiline=True, placeholder=input_placeholder)
            user_input = parse_user_instruct(user_input=user_input)
            if not user_input:
                continue
            Logger.info(f"Begin to process user input: {user_input}")

            is_generating = True
            await runtime.publish_message(
                QueryParseResult(original_query=user_input),
                TopicId(type=chat_topic_type, source=session_id),
            )
            while is_generating:
                await asyncio.sleep(0.5)

            Console().print(Markdown("-" * 4))

        except KeyboardInterrupt:
            os._exit(status=0)
        except EOFError:
            os._exit(0)


asyncio.run(main())
